name: 'OptCD tool'
description: 'Demo tool for OptCD'

inputs:
  yaml-file:
    description: 'YAML file to be modified'
    required: true
  gh-pat-token:
    description: 'GitHub personal access token'
    required: true

#outputs:
#  unnecessary-folders:
#    description:
#    value:
#  responsible-plugins:
#    description:
#    value:

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.gh-pat-token }}
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "${{ github.action_path }}"/requirements.txt
      shell: bash
    
    - name: Generate the modified YAML file
      run: python "${{ github.action_path }}"/main.py "${{ inputs.yaml-file }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Push the modified YAML file
      shell: bash
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .github/workflows/modified-workflow.yml
        git commit -m "add modified workflow"
        git push
        
    - name: Run the modified YAML file
      uses: actions/github-script@v7.0.1
      with:
        github-token: ${{ inputs.gh-pat-token }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: "ogul1",
            repo: "workflow-that-uses-base-action",
            workflow_id: "modified-workflow.yml",
            ref: "main"
          })
